### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/ddmrp#236]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] ddmrp
- [x] ddmrp_adjustment - By @LoisRForgeFlow - #356
- [x] ddmrp_chatter
- [ ] ddmrp_coverage_days
- [x] ddmrp_cron_actions_as_job - By @LoisRForgeFlow - #418
- [x] ddmrp_exclude_moves_adu_calc - By @LoisRForgeFlow - #357
- [x] ddmrp_history
- [ ] ddmrp_packaging
- [x] ddmrp_product_replace - By @LoisRForgeFlow - #354
- [x] ddmrp_warning
- [ ] stock_buffer_capacity_limit
- [x] stock_buffer_route - By @BernatPForgeFlow - #351
- [x] stock_buffer_sales_analysis - By @BernatPForgeFlow - #342

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
