### ISSUE TITLE
[11.0] Roadmap

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/ddmrp#5]
* Strategic Inventory Positioning
  - [ ] Display the parent-child relationships in the critical path, in the BOM Matrix
* Buffer Profiles and Levels
  - [ ] Blended ADU calculation method.
  - [ ] ADU Exceptions
  - [ ] Fix min-max calculation method
* Dynamic Adjustments
  - [ ] Zone Adjustment Factor (option for days of DLT and factor)
* Demand Driven Planning
  - [ ] Long term Order spike horizon and spike threshold
  - [ ] Setting different Order Spike Threshold criteria (now 50% of TOG is the only supported)
  - [ ] Implement proper MRP for Decoupled Explosion, instead of MTO rules. Possibly implementing https://github.com/Eficent/manufacture/tree/8.0-multi_level_mrp or a more recent version from Wim Audenaert.
* Visible and Collaborative Execution
  - [ ] Prioritized share
  - [ ] Lead time Alerts
  - [ ] Projected On-hand Alert
  - [ ] Material synchronization alert for dependent points.
* Analytics
  - [ ] On-hand Performance Run Chart from $ perspective
  - [ ] Parts Flow Index Chart
  - [ ] On-Hand Position Distribution Chart
  - [ ] Suppliers Disruption Report
  - [ ] Add more fields to history: ADU, qualified demand...
* Demand Driven Model Projections
* Technical
  - [ ] Use queues to run the recalculated buffer adjustments near real time.
  - [ ] Identify performance bottlenecks and improve (database indexes, code optimization)

PRs:
* [ ] forward port https://github.com/Eficent/ddmrp/pull/57
* [ ] forward port https://github.com/Eficent/ddmrp/pull/55
* [ ] Fix the rounding on the "unit" UoM from odoo.
