### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by max3903** [OCA/ddmrp#7]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Dependencies

https://github.com/OCA/web/issues/739

- [ ] ~web_tree_many2one_clickable - not needed, https://github.com/OCA/web/issues/872~
- [x] web_widget_x2many_2d_matrix - https://github.com/OCA/web/pull/871
- [x] web_widget_bokeh_chart - by @arkostyuk
- [x] web_tree_dynamic_colored_field - by @arkostyuk

https://github.com/OCA/manufacture/issues/226

- [x] mrp_mto_with_stock - by @bodedra
- [x] mrp_bom_location - by @lreficent https://github.com/OCA/manufacture/pull/285

https://github.com/OCA/manufacture-reporting/issues/31

- [x] report_mrp_bom_matrix - by @mpanarin
- [x] mrp_bom_current_stock

https://github.com/OCA/server-tools/issues/1008

- [x] base_cron_exclusion - by @bodedra

https://github.com/OCA/stock-logistics-warehouse/issues/343

- [x] stock_putaway_product
- [x] stock_orderpoint_manual_procurement - by @bodedra - https://github.com/OCA/stock-logistics-warehouse/pull/385
- [x] stock_orderpoint_uom - by @bodedra - https://github.com/OCA/stock-logistics-warehouse/pull/386
- [x] stock_orderpoint_manual_procurement_uom - by @bodedra - https://github.com/OCA/stock-logistics-warehouse/pull/387
- [x] stock_warehouse_orderpoint_stock_info
- [x] stock_warehouse_orderpoint_stock_info_unreserved - https://github.com/OCA/stock-logistics-warehouse/pull/377
- [x] stock_demand_estimate - https://github.com/OCA/stock-logistics-warehouse/pull/381
- [x] stock_available_unreserved

## Modules to migrate

- [x] ddmrp
- [x] ddmrp_history
- [x] ddmrp_adjustment
- [ ] ddmrp_product_replace

**Comment by LoisRForgeFlow** [comment]
We can consider this done.
